# Generated by Django 5.1.3 on 2024-11-14 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0002_alter_user_info_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='request_friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='friend_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
