# Generated by Django 5.1.3 on 2024-11-15 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messenger', '0003_user_info_request_friend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='private_messages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='private_messages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AddConstraint(
            model_name='private_rooms',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_room_between_users'),
        ),
    ]
